import { clientRepository } from "./repository";
import { leadRepository } from "@/modules/leads/repository";
import { LeadNotFoundError } from "@/modules/leads/errors";
import { ClientNotFoundError, LeadAlreadyConvertedError } from "./errors";
import type { UpdateClientInput } from "./schema";

export class ClientService {
  /**
   * Converts a lead into a client. Direct call into the leads module's
   * repository (same simple, no-event-bus pattern used for lead creation
   * from form submissions) — one logical operation, not decoupled.
   */
  async createFromLead(organizationId: string, leadId: string) {
    const lead = await leadRepository.findById(organizationId, leadId);

    if (!lead) {
      throw new LeadNotFoundError();
    }

    const existing = await clientRepository.findByLeadId(leadId);

    if (existing) {
      throw new LeadAlreadyConvertedError();
    }

    const client = await clientRepository.create({
      organizationId,
      leadId: lead.id,
      name: lead.name,
      email: lead.email,
      company: lead.company,
      phone: lead.phone,
      // portalToken is auto-generated by the schema's $defaultFn
    });

    // Reasonable default: a lead that's been converted is, by definition,
    // won. Not explicitly required by the roadmap, but leaving lead.status
    // stale (e.g. still "qualified") after conversion would be confusing
    // in the leads list — flag if you'd rather this stay manual.
    await leadRepository.updateStatus(lead.id, "won");

    return client;
  }

  async getById(organizationId: string, id: string) {
    const client = await clientRepository.findById(organizationId, id);
    if (!client) throw new ClientNotFoundError();
    return client;
  }

  async list(
    organizationId: string,
    options?: { limit?: number; offset?: number },
  ) {
    return clientRepository.findByOrganizationId(organizationId, options);
  }

  async update(organizationId: string, id: string, data: UpdateClientInput) {
    const client = await clientRepository.findById(organizationId, id);
    if (!client) throw new ClientNotFoundError();
    return clientRepository.update(id, data);
  }

  async getByPortalToken(token: string) {
    const client = await clientRepository.findByPortalToken(token);
    if (!client) throw new ClientNotFoundError();
    return client;
  }
  // add inside ClientService
  async delete(organizationId: string, id: string) {
    const client = await clientRepository.findById(organizationId, id);
    if (!client) throw new ClientNotFoundError();
    await clientRepository.delete(id);
  }
}

export const clientService = new ClientService();
