import { db } from "@/db";
import { clientRepository } from "./repository";
import { leadRepository } from "@/modules/leads/repository";
import { LeadNotFoundError } from "@/modules/leads/errors";
import { projectRepository } from "@/modules/projects/repository";
import { ClientNotFoundError, LeadAlreadyConvertedError } from "./errors";
import type { UpdateClientInput } from "./schema";

type ConvertLeadProjectInput = {
  name: string;
  description?: string | null;
  deadline?: string | null;
};

export class ClientService {
  /**
   * Converts a lead into a client, and optionally creates a starter project
   * in the same operation. Everything below runs inside one transaction:
   * if the project insert fails, the client insert and the lead's status
   * update both roll back too — you never end up with a client that exists
   * but no corresponding lead status change, or a half-converted lead.
   *
   * `project` omitted/null → client only (this is the pre-existing manual
   * "Convert to client" button's behavior, unchanged).
   * `project` provided → client + project, both created before the lead is
   * marked "won".
   */
  async createFromLead(
    organizationId: string,
    leadId: string,
    project?: ConvertLeadProjectInput | null,
  ) {
    return db.transaction(async (tx) => {
      const lead = await leadRepository.findById(organizationId, leadId, tx);
      if (!lead) {
        throw new LeadNotFoundError();
      }

      // Idempotency guard — must run inside the same transaction as the
      // insert below, using the tx connection, or a second conversion
      // request racing the first could both pass this check before either
      // commits (classic check-then-act race). Postgres's default
      // read-committed isolation won't save us here on its own; the guard
      // only holds because both the check and the insert happen on the
      // same transaction and clients.leadId has no unique constraint to
      // fall back on as a last line of defense — worth adding one if this
      // ever needs to be bulletproof under real concurrent load.
      const existing = await clientRepository.findByLeadId(leadId, tx);
      if (existing) {
        throw new LeadAlreadyConvertedError();
      }

      const client = await clientRepository.create(
        {
          organizationId,
          leadId: lead.id,
          name: lead.name,
          email: lead.email,
          company: lead.company,
          phone: lead.phone,
          // portalToken is auto-generated by the schema's $defaultFn
        },
        tx,
      );

      let createdProject = null;
      if (project) {
        createdProject = await projectRepository.create(
          {
            organizationId,
            clientId: client.id,
            name: project.name,
            description: project.description ?? null,
            deadline: project.deadline ?? null,
            // stage intentionally omitted — falls through to the schema's
            // default ("planning"), same default CreateProjectDialog relies on.
          },
          tx,
        );
      }

      // A lead that's been converted is, by definition, won — same
      // reasoning as before, now just also covering the project-creation path.
      await leadRepository.updateStatus(lead.id, "won", tx);

      return { client, project: createdProject };
    });
  }

  async getById(organizationId: string, id: string) {
    const client = await clientRepository.findById(organizationId, id);
    if (!client) throw new ClientNotFoundError();
    return client;
  }

  async list(
    organizationId: string,
    options?: { limit?: number; offset?: number },
  ) {
    return clientRepository.findByOrganizationId(organizationId, options);
  }

  async update(organizationId: string, id: string, data: UpdateClientInput) {
    const client = await clientRepository.findById(organizationId, id);
    if (!client) throw new ClientNotFoundError();
    return clientRepository.update(id, data);
  }

  async getByPortalToken(token: string) {
    const client = await clientRepository.findByPortalToken(token);
    if (!client) throw new ClientNotFoundError();
    return client;
  }

  async delete(organizationId: string, id: string) {
    const client = await clientRepository.findById(organizationId, id);
    if (!client) throw new ClientNotFoundError();
    await clientRepository.delete(id);
  }
}

export const clientService = new ClientService();